let PRODUCTS_ARE_LOADED = 'PRODUCTS_ARE_LOADED';
let DIFFERENT_PRODUCT_ARE_LOADED = 'DIFFERENT_PRODUCT_ARE_LOADED';
let ADD_TO_CART = 'ADD_TO_CART';
let REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export {
    DIFFERENT_PRODUCT_ARE_LOADED,
    PRODUCTS_ARE_LOADED,
    ADD_TO_CART,
    REMOVE_FROM_CART
}